kind: pipeline
name: default

steps:
- name: cloning repo
  image: alpine:3.10.2
  volumes:
    - name: repo
      path: /order/
  commands:
    - cd /
    - apk update
    - apk add git
    - git clone "https://github.com/testinguser883/webapp" /order

- name: building repo
  image: golang:alpine
  volumes:
    - name: repo
      path: /order/
  commands:
    - go build -o /order/order_exe main.go
    - /order/order_exe
    
  - name: building repo test
  image: golang:alpine
  volumes:
    - name: repo
      path: /orders/
  commands:
    - go build -o /orders/order_exe main.go
    - /orders/order_exe
    
    
volumes:
- name: repo
  temp: {}
